demo/urls.py
from django.conf.urls import url
from demo import views
from django.views.generic import TemplateView,RedirectView
urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^publisher/$',views.publisher,name='publisher'),
    url(r'^forms/$',views.form,name='forms'),
    url(r'^zidingyifields/$', views.testlist, name='zidingyifields'),
    url(r'^tasks/$', views.ShowTasksView.as_view(), name='tasks'),
    url(r'^task/(?P<task_id>\d+)/$', views.DisplaySingleTaskView.as_view(), name='tasks'),
    url(r'^success',views.success,name='success'),
    url(r'^addtask',views.AddTaskView.as_view(),name='addtask'),
    url(r'^ajax',views.more_publisher,name='ajax'),
    url(r'^ajax',views.more_publisher,name='ajax'),
    url(r'^rest_framework/$',views.PublisherListView.as_view(),name='rest'),
    url(r'^rest_framework/(?P<pk>[0-9]+)$',views.publisher_detail,name='publisher_detail'),
    url(r'^signal/$',views.signal_view,name='signal'),
    url(r'^disconnect_signal/$', views.disconnect_signal, name='disconnect_signal'),
    url(r'^langues/$',views.languase,name='languase'),
    url(r'^addlangues/$', views.add_languase, name='addlanguase'),
]

django_jijie/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('demo.urls')),
    url(r'^demo2/',include('demo2.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from demo.fields import *
from django.core.validators import ValidationError
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class IncompleteCityManager(models.Manager):
    def get_queryset(self):
        return super(IncompleteCityManager,self).get_queryset().filter(city='上海')
class StateProvinceManager(models.Manager):
    def get_queryset(self):
        return super(StateProvinceManager,self).get_queryset().filter(state_province='北京')
class PublisherManager(models.Manager):
    def cityqueryset(self):
        return self.filter(city='上海')
    def stateProvince(self):
        return self.filter(state_province='北京')
class Publisher(models.Model):
    name=models.CharField(max_length=30,verbose_name='名称')
    address=models.CharField(max_length=50,verbose_name='地址')
    city=models.CharField(max_length=60,verbose_name='市')
    state_province=models.CharField(max_length=30,verbose_name='省')
    country=models.CharField(max_length=50,verbose_name='国家')
    website=models.URLField(verbose_name='网址')
    publisherLists=models.Manager()
    objects=models.Manager()
    incompleteCity=IncompleteCityManager()
    stateProvince=StateProvinceManager()
    publisherManager=PublisherManager()
    class Meta:
        db_table='demo_publisher'
        verbose_name='出版社'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.name
class Author(models.Model):
    name=models.CharField(max_length=30,verbose_name='名字')
    class Meta:
        db_table = 'demo_author'
        verbose_name='作者'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.name
class AuthorDetail(models.Model):
    sex=models.BooleanField(max_length=1,choices=((0,'男'),(1,'女')),verbose_name='性别')
    email=models.EmailField(verbose_name='邮箱')
    address=models.CharField(max_length=50,verbose_name='住址')
    birthday=models.DateField(verbose_name='出生日期')
    author=models.OneToOneField(Author,verbose_name='作者')
    class Meta:
        db_table = 'demo_authordetail'
        verbose_name='作者详情'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.author.name
class Book(models.Model):
    title=models.CharField(max_length=100,verbose_name='书名')
    authors=models.ManyToManyField(Author,verbose_name='作者')
    publisher=models.ForeignKey(Publisher,verbose_name='出版社')
    publication_date=models.DateField(verbose_name='出版日期')
    price=models.DecimalField(max_digits=5,decimal_places=2,default=10,verbose_name='价格')
    class Meta:
        db_table = 'demo_book'
        verbose_name='书籍'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.title

def validate_pre(value):
    print 'validate_pre'
    if not value.startswith('a'):
        raise ValidationError('u must start with a', code='invalid')


class FormEntry(models.Model):
    author=models.CharField(max_length=10,validators=[validate_pre])
    title=models.CharField(_(u'title'),max_length=100)
    def __str__(self):
        return self.author
    class Meta:
        verbose_name = '高级测试'
        verbose_name_plural = verbose_name


class ListTest(models.Model):
    labels=ListFiled()
    def __str__(self):
        return "%s" % self.labels

demo/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import FormEntry,Publisher
from django.core.validators import ValidationError
class SubInputText(forms.TextInput):
    class Media:
        css={
            'all': ('input.css',)
        }
class AddForm(forms.ModelForm):
    class Meta:
        model=FormEntry
        fields=['author','title']
        widgets={
            'author':forms.Textarea(attrs={'cols':'20','row':1}),
            'title':SubInputText(),
        }
    # def clean_author(self):
    #     print ('clean author')
    #     data=self.cleaned_data['author']
    #     if 'allen' not in data:
    #         raise ValidationError('no in allen')
    #     return data
    def clean(self):
        author=self.cleaned_data['author']
        title=self.cleaned_data['title']
        object=FormEntry.objects.filter(author=author,title=title)
        if object:
            raise ValidationError('no in allen')
class SetCityForm(forms.Form):
    city=forms.CharField()
    _selected_action=forms.CharField(widget=forms.MultipleHiddenInput)
class AddTaskForm(forms.ModelForm):
    class Meta:
        model=Publisher
        fields=['id','name',]

demo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,HttpResponse,HttpResponseRedirect,reverse,Http404
from demo.models import *
from django.views.generic import TemplateView,ListView,View
from .serializers import PublisherSerializer
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from . import signals
from django.utils.translation import ugettext as _
import qiniu
import uuid
from django_jijie import settings
# Create your views here.
from .forms import *
def success(request):
    return render(request,'success.html',locals())
def index(request):

    return render(request,'index.html',{'tmpValue':[1,2,3]})
def form(request):
    if request.method=='POST':
        forms=AddForm(request.POST)
        if not forms.is_valid():
            forms = AddForm()
            print 'invalid'
            return render(request, 'form.html', {'form': forms})
        author=forms.cleaned_data['author']
        title=forms.cleaned_data['title']
        print author,title
    forms=AddForm()
    return render(request,'form.html',{'form':forms})
def testlist(request):
    test=ListTest()
    test.labels=["python","django"]
    test.labels.append('allen')
    test.save()
    return HttpResponse('success')

class ShowTasksView(ListView):
    template_name = 'task.html'
    model = Publisher
    context_object_name = 'my_favorite_publishers'
class DisplaySingleTaskView(TemplateView):
    template_name = 'single_task.html'
    context_object_name='task'
    def get_context_data(self, **kwargs):
        context=super(DisplaySingleTaskView,self).get_context_data(**kwargs)
        task_id=self.kwargs.get("task_id",0)
        context['task']=Publisher.publisherLists.get(id=task_id)
        return context
class AddTaskView(View):
    def get(self,request):
        return render(request,'add_task.html',{'form':AddForm})
    def post(self,request):
        form=AddTaskForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('success'))
def publisher(request):
    return render(request,'publisher.html',{"showType":"所有的列表","publisherList":Publisher.publisherManager.cityqueryset()})

def more_publisher(request):
    if request.is_ajax():
        objects=Publisher.publisherLists.all()
        data=get_json_objects(objects,Publisher)
        return HttpResponse(data,content_type='application/json')
    else:
        return render(request, 'ajax.html', {})

def json_filed(field_data):
    if isinstance(field_data,str):
        return "\""+field_data+"\""
    if isinstance(field_data,bool):
        if field_data=='False':
            return 'false'
        else:
            return 'true'
    return str(field_data)
def json_encode_dict(dict_data):
    json_data = "{"
    for (k,v) in dict_data.items():
        json_data=json_data+json_filed(k)+": "+json_filed(v)+", "
    json_data=json_data[:-2]+"}"
    return json_data

def json_encode_list(list_data):
    json_res="["
    for item in list_data:
        json_res=json_res+json_encode_dict(item)+", "
    return json_res[:-2]+"]"
def get_json_objects(objects,model_meta):
    concrete_model=Publisher._meta.concrete_model
    list_data=[]
    for obj in objects:
        dict_data={}
        for field in concrete_model._meta.local_fields:
            if field.name=='id':
                continue
            value=field.value_from_object(obj)
            dict_data[field.name]=value
        list_data.append(dict_data)
    data=json_encode_list(list_data)
    return data
class PublisherListView(APIView):
    def get(self,request,format=None):
        publisher=Publisher.publisherLists.all()
        serializer=PublisherSerializer(publisher,many=True)
        return Response(serializer.data)
    def post(self,request,format=None):
        serializer=PublisherSerializer(data=request.data,many=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
@api_view(['GET','PUT','DELETE'])
def publisher_detail(request,pk):
    try:
        publiser=Publisher.objects.get(pk=pk)
    except Publisher.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method=='GET':
        serializer=PublisherSerializer(publiser)
        return Response(serializer.data)
    elif request.method=='PUT':
        serializer=PublisherSerializer(publiser,request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    elif request.method=='DELETE':
        publiser.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
def signal_view(request):
    signals.signalAllen.send(sender=None,allen='test')
    return HttpResponse("signals")
def disconnect_signal(request):
    signals.signalAllen.disconnect(signals.signal_callback)
    return HttpResponse("注销成功")
def languase(request):
    return render(request,'languase.html',{'test':_('test')})
def add_languase(request):
    if request.method=='GET':
        return render(request,'add_article_lanuage.html',{'form':AddForm()})
    else:
        return HttpResponse(_('ok'))
def upload(request):
    key=str(uuid.uuid1()).replace('-','')
    q=qiniu.Auth(access_key=settings.QINIU_ACCESSKEY,secret_key=settings.QINIU_SECRETKEY)

demo/templates/add_article_lanuage.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="ok" value="{% trans 'ok' %}">
</form>
</body>
</html>

demo/templates/add_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="add" value="add">
</form>
</body>
</html>

demo/templates/ajax.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
     <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript">
        // using jQuery
        $(document).ready(function () {
             function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
             $('button').click(function () {
                alert("aa");
                $.ajax({
                    type:"GET",
                    url:{% url 'ajax' %},
                    dataType:'json',
                    success:function (data) {
                        json_str=JSON.stringify(data)
                        json_data=JSON.parse(json_str)
                        for (var i in json_data){
                            item=json_data[i];
                            $('ul').append('<li>'+item.name+" "+item.address+'</li>');
                        }
                    }
                });
            });
        });
    </script>
</head>
<body>
<div>
    <div class="container">
        <div class="container">
            <h3>Publisher</h3>
            <ul>
                <li>Results:</li>
            </ul>
            <button class="btn get-more" id="more">Get More Publisher</button>
        </div>
    </div>
</div>
</body>
</html>

demo/templates/change_form.html
{% extends 'admin/change_form.html' %}
{% block form_top %}
    <p>注意：不要讲作者写错哦</p>
{% endblock %}

demo/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<label>增加诗词信息:</label>
<form action="{% url 'forms' %}" method="post">
    {% csrf_token %}
     {{ form.as_p }}
    <input type="submit" value="OK">
</form>
</body>
</html>

demo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django</title>
</head>
<body>
<h1>Hello,Django</h1>
{% for i in tmpValue %}
    {% if i==1 %}
        {{ i }}
    {% endif %}
{% endfor %}
<div>
    {{ 1+2 }}
    {{ 1/2 }}
    {{ 10%3 }}
    {{ 2**3 }}
    {% set tmpInt=10 %}
    {{ tmpInt }}

    {{ -1|abs }}
    {{ 'abc'|capitalize|allen_lower }}
</div>
</body>
</html>

demo/templates/languase.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% trans test %}
<p>{% trans "dangdangdang" %}</p>
</body>
</html>

demo/templates/publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ showType }}
<br>
{% for pub in publisherList %}
    <p>==========================================</p>
    {{ pub.name }}
    <br>
     {{ pub.address }}
    <br>
     {{ pub.city }}
    <br>
     {{ pub.state_province }}
    <br>
     {{ pub.country }}
    <br>
     {{ pub.website }}
    <br>
{% endfor %}
</body>
</html>

demo/templates/resultes.html
<ul>
    <p>{{ name }}</p>
    {% for poem in poems %}
        <li>{{ poem.title }}</li>
        <li>{{ poem.publisher }}</li>
        <li>{{ poem.publication_date }}</li>
        <li>{{ poem.price }}</li>
    {% endfor %}
</ul>

demo/templates/set_city.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <ul>
        {% for ob in objects %}
            <li>{{ ob }}</li>
        {% endfor %}
    </ul>
    <input type="hidden" name="action" value="set_type_action">
    <input type="hidden" name="post" value="yes">
    <input type="submit" name="apply" value="set">
    </form>
{% endblock %}

demo/templates/single_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ task }}
</body>
</html>

demo/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>success</h1>
</body>
</html>

demo/templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for publisher in my_favorite_publishers %}
    <li>{{ publisher.name }}</li>
{% endfor %}
</body>
</html>

demo/templates/task_list.html
{% for publisher in publisher_list %}
    <li>{{ publisher.name }}</li>
{% endfor %}